server:
  port: 8080

spring:
  application:
    name: reliable-producer

  jackson:
    # 日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
    # 忽略 null 的属性值
    default-property-inclusion: NON_NULL

  rabbitmq:
    virtual-host: "/"
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 确认消息已发送到交换机
    publisher-confirm-type: correlated
    # 确认消息已发送到队列
    publisher-returns: true