server:
  # 设置服务器端口
  port: 8080

spring:
  application:
    # 应用名称设置
    name: feign-basic

  cloud:

    # === Spring Cloud 服务发现 ===
    discovery:
      enabled: true

    # === Spring Cloud 负载均衡 ===
    loadbalancer:
      nacos:
        enabled: true

    # === Spring Cloud 服务注册 ===
    service-registry:
      auto-registration:
        enabled: true

    # === Nacos 中间件配置 ===
    nacos:
      discovery:
        server-addr: localhost:8848

    # === Open Feign 配置 ===
    openfeign:
      # --- 懒加载设置，默认 false ---
      lazy-attributes-resolution: false
      # --- 客户端配置 ---
      client:
        # 是否配置文件优先配置类，默认：true，即配置文件覆盖配置类
        default-to-properties: true
        config:
          # 对 foo-service 客户端的定制
          foo-service:
            # 打印日志等级，default-to-properties=true 的缘故
            # 故此配置覆盖 FooClientConfiguration 设置的 FULL
            logger-level: BASIC


# === 日志 ===
logging:
  level:
    # -- FooClient Feign 客户端日志级别为 DEBUG ---
    io.github.reionchan.client.FooClient: DEBUG

# === Spring 环境引入 Maven 变量 ===
# 使用 @ 符号包含 maven 变量
# 详细：https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering
maven:
  version: @project.version@