server:
  # 设置服务器端口
  port: 8080

spring:
  application:
    # 应用名称设置
    name: feign-extensibility

  cloud:

    # === Spring Cloud 服务发现 ===
    discovery:
      enabled: true

    # === Spring Cloud 负载均衡 ===
    loadbalancer:
      nacos:
        enabled: true

    # === Spring Cloud 服务注册 ===
    service-registry:
      auto-registration:
        enabled: true

    # === Nacos 中间件配置 ===
    nacos:
      discovery:
        server-addr: localhost:8848

    # === Open Feign 配置 ===
    openfeign:
      # --- 客户端配置 ---
      client:
        config:
          # 对 foo-service 客户端的定制
          foo-service:
            # 打印日志等级，default-to-properties=true 的缘故
            # 故此配置覆盖 FooClientConfiguration 设置的 FULL
            logger-level: BASIC
            # 针对当前客户端是否开启 micrometer 自动装配
            micrometer:
              enabled: true
      # --- micrometer 配置 ---
      micrometer:
        # 是否对所有客户端开启 micrometer 自动装配
        enabled: true

# === 日志 ===
logging:
  level:
    # FooClient Feign 客户端日志级别为 DEBUG
    io.github.reionchan.client.FooClient: DEBUG
  #pattern:
    # 日志等级模式中添加显示 traceId spanId
    #level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# === Spring Boot Actuator Web Endpoint 配置 ===
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # --- 默认配置 ---
  defaults:
    metrics:
      export:
        # 是否在 /actuator/metrics 端点导出标量，默认 true
        enabled: true
  # --- simple 配置 ---
  simple:
    metrics:
      export:
        # 是否在 /actuator/metrics 端点导出标量，默认 true
        # 此设置优先级高于上面的 defaults 设置
        enabled: true

# === Spring 环境引入 Maven 变量 ===
# 使用 @ 符号包含 maven 变量
# 详细：https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering
maven:
  version: @project.version@
