server:
  # 设置服务器端口
  port: 8080

spring:
  application:
    # 应用名称设置 gateway-nacos
    name: gateway-nacos

  cloud:

    # === Spring Cloud 服务发现 ===
    discovery:
      # 开启服务发现，默认 true
      enabled: true

    # === Spring Cloud 负载均衡 ===
    loadbalancer:
      # 默认负载均衡器时懒加载，在使用到时才去装载配置类
      eager-load:
        # 通过指定服务名称来将此服务的负载均衡器在启动时进行装载
        clients: ${spring.application.name}

      # 启用 Nacos 的负载均衡器，默认 false
      #
      # false 时，将使用 Spring Cloud 的 RoundRobinLoadBalancer 负载均衡器
      # 原理：
      #   Spring Cloud 的 LoadBalancerClientFactory 生成子 context 时，
      #   向该 context 注册 LoadBalancerClientConfiguration 配置类，
      #   其中就有 RoundRobinLoadBalancer 类型的 bean 装载
      #
      # true 时，将使用 NacosLoadBalancer 负载均衡器
      # 原理：
      #   nacos-discovery 模块自动配置类 LoadBalancerNacosAutoConfiguration 上面的注解
      #     @LoadBalancerClients(defaultConfiguration = NacosLoadBalancerClientConfiguration.class)
      #   引人的 NacosLoadBalancerClientConfiguration 配置类，其中就有 NacosLoadBalancer 类型的 bean 装载
      #
      # 注意：
      #   @LoadBalancerClients 配置的 defaultConfiguration 配置类会在子 context 装载，即 NacosLoadBalancer 被隔离到子 context 中
      #   如果不小心将 NacosLoadBalancerClientConfiguration 放入主服务启动扫描器的扫描路径中，会使得 NacosLoadBalancer 构造器中的
      #   ObjectProvider<ServiceInstanceListSupplier> 参数构造时 name (来源于环境变量：loadbalancer.client.name) 为空，导致最终
      #   负载均衡调用时报空指针异常。（Spring Cloud 负载均衡策略配置中明确指出更换负载均衡算法时的配置类不应被标注 @Configuration 或自动装配
      #   扫描路径中，详见：https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#switching-between-the-load-balancing-algorithms）
      #   之所以要这样处理，是因为 Spring 想实现利用 @LoadBalancerClient 或者 @LoadBalancerClients 机制来自定义指定负载均衡策略，而又免于
      #   定义多个负载均衡时被相互覆盖问题
      nacos:
        enabled: true

    # === Spring Cloud 服务注册 ===
    service-registry:
      auto-registration:
        # 是否开启服务自动注册，默认 true
        # false 时，本服务将不会注册到服务注册中心 nacos
        # 原理：
        #   使 NacosServiceRegistryAutoConfiguration、
        #      AutoServiceRegistrationAutoConfiguration
        #   自动装载配置类失效
        enabled: true

    # === Nacos 中间件配置 ===
    nacos:
      # nacos 通用服务器地址配置
      #server-addr: localhost:8848
      # nacos 服务发现实现
      discovery:
        # 服务发现服务器地址
        server-addr: localhost:8848

    # 网关配置
    gateway:
      # 网关服务发现
      discovery:
        locator:
          # 开启网关与服务发现集成
          enabled: true

# logging
logging:
  level:
    # 设置 gateway 相关方法日志级别为 TRACE
    org.springframework.cloud.gateway: TRACE