server:
  port: 8082

spring:
  application:
    name: reliable-consumer

  jackson:
    # 日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
    # 忽略 null 的属性值
    default-property-inclusion: NON_NULL

  rabbitmq:
    virtual-host: "/"
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 250
        concurrency: 1