{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Demo MethodA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MethodA Called Time Gauge (Realtime)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "ce1f614f", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "micrometer-traces-opentelemetry"
       ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "MethodA Called Time (Avg)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(demo_milliseconds_sum/demo_milliseconds_count)",
     "legendFormat": "methodA Avg"
    }
   ]
  },
  {
   "title": "MethodA Called Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(demo_milliseconds_count[1m])",
     "legendFormat": "{{demo_call_method}}"
    }
   ]
  },
  {
   "title": "Recent 20 Logs",
   "type": "table",
   "gridPos": { "h": 24, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"micrometer-logging-opentelemetry\"} |= `do`"
    }
   ]
  },
  {
   "title": "MethodA Called Histogram Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Top 5 methodA Slow Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "499d609a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "micrometer-logging-opentelemetry"
       ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}