{
 "title": "Demo",
 "time": { "from": "2023-11-29T11:45:26.874Z", "to": "2023-11-29T11:49:23.007Z" },
 "panels": [
  { "title": "Demo MethodA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MethodA Called Time Gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_milliseconds_sum/demo_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 MethodA Called Cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, demo_milliseconds_sum/demo_milliseconds_count)",
     "legendFormat": "{{demo_call_method}}"
    }
   ]
  },
  {
   "title": "MethodA Called Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(demo_milliseconds_sum/demo_milliseconds_count)",
     "legendFormat": "methodA Avg"
    }
   ]
  },
  {
   "title": "MethodA Called Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(demo_milliseconds_count[1m])",
     "legendFormat": "{{demo_call_method}}"
    }
   ]
  },
  {
   "title": "MethodA Called Histogram Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(demo_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}