server:
  # 设置服务器端口
  port: 9000

spring:
  application:
    # 应用名称设置
    name: foo-service

  cloud:

    # === Spring Cloud 服务发现 ===
    discovery:
      enabled: true

    # === Spring Cloud 负载均衡 ===
    loadbalancer:
      nacos:
        enabled: true

    # === Spring Cloud 服务注册 ===
    service-registry:
      auto-registration:
        enabled: true

    # === Nacos 中间件配置 ===
    nacos:
      discovery:
        server-addr: localhost:8848

# === SpringDoc ===
springdoc:
  # 设置是否显示 actuator 端口
  show-actuator: false

# === Spring 环境引入 Maven 变量 ===
# 使用 @ 符号包含 maven 变量
# 详细：https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering
maven:
  version: @project.version@