server:
  # 设置服务器端口
  port: 8080

spring:
  application:
    # 应用名称设置 gateway-redis-ratelimit
    name: gateway-ratelimit

  data:
    # Redis 中间件配置
    redis:
      host: localhost
      port: 6379
      password: pleaseChangeMe

# logging
logging:
  level:
    # 设置 gateway 相关方法日志级别为 TRACE
    org.springframework.cloud.gateway: TRACE