server:
  port: 8080

spring:
  application:
    name: micrometer-prometheus-grafana

management:
  endpoints:
    web:
      exposure:
        # 默认情况，Prometheus 监控指标是由 /actuator/prometheus 路径暴露的
        #
        # 需要在 Prometheus 服务器配置文件 prometheus.yml 做如下配置
        # ---------------------------------------------
        # scrape_configs:
        #  - job_name: "micrometer-prometheus"
        #    metrics_path: "/actuator/prometheus"
        #    static_configs:
        #      - targets: ["localhost:8080"]
        # ---------------------------------------------
        include: health,metrics,prometheus

  # === Prometheus 监控指标配置 ===
  prometheus:
    metrics:
      export:
        # 将指标信息推送给 Push Gateway
        #
        # Push Gateway 服务器下载地址：
        #   https://github.com/prometheus/pushgateway
        #
        # 需要在 prometheus.yml 中配置 pushgateway 相关配置
        # ----------------------------------------------
        # scrape_configs:
        #  - job_name: "micrometer-prometheus"
        #    static_configs:
        #      - targets: ["localhost:9090"]
        # -----------------------------------------------
        pushgateway:
          # pushgateway 地址
          base-url: http://localhost:9091
          # 默认 false 关闭推送功能，设置 true 启用
          enabled: false
