server:
  port: 8080

spring:
  application:
    name: micrometer-metrics-opentelemetry

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  # 全局指标设置
  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      # 百分位值
      percentiles:
        demo:
          percentiles: [0.25, 0.5, 0.75, 0.90, 0.95]
#      # 百分位直方图
      percentiles-histogram:
        demo: true
#      # 最小期望值
#      minimum-expected-value:
#        demo: 90ms
#      # 最大期望值
#      maximum-expected-value:
#        demo: 900ms
#      # Service Level Objectives 服务水平目标
#      slo:
#        demo: 100, 200, 400, 800, 1000

  # === OpenTelemetry Collector 遥测数据收集器配置 ===
  otlp:
    metrics:
      export:
        enabled: true
        step: 10s
        # 默认 OTLP 服务器地址
        url: http://localhost:4318/v1/metrics
