server:
  port: 8088
  # 优雅的关闭服务器
  shutdown: graceful

spring:
  # === 应用配置 ===
  application:
    name: loadbalancer

  cloud:
    # === 负载均衡配置 ===
    loadbalancer:
      # --- 预先加载负载均衡客户端上下文 ---
      eager-load:
        # 填写预先加载的服务名称，此为列表形式
        clients:
          - loadbalancer
      # --- Nacos 负载均衡器是否启用 ---
      nacos:
        enabled: false

    # === 服务注册配置 ===
    service-registry:
      # --- 设置自动注册快速失败 ---
      auto-registration:
        # true 时，强制依赖服务注册客户端实现，否则启动异常
        fail-fast: true

    # === Nacos 配置 ===
    nacos:
      # --- Nacos 服务发现配置 ---
      discovery:
        # 服务发现服务器地址
        server-addr: localhost:8848
        # 设置负载均衡权重 (Nacos 实现的负载均衡器读取此属性值)
        weight: 8
        # 设置此实例是否是临时性（此处设置为 false，即 persistent 永久性，才会生成 instanceId）
        # 更改为 false 后，如果启动服务报错，请参考 https://zhuanlan.zhihu.com/p/571875080
        ephemeral: false
        # 负载均衡元数据（一些扩展属性）
        metadata:
          # 权重数据 （设置给 ZonePreferenceServiceInstanceListSupplier 读取）
          weight: 8
          # 区域标识 （设置给 ZonePreferenceServiceInstanceListSupplier 读取）
          zone: bar-zone
          # 生成 instanceId 方法，默认 simple，Nacos 2.3.0 支持 snowflake
          # 参考：https://github.com/alibaba/nacos/issues/9001
          preserved.instance.id.generator: simple
          hint: bar-hint

management:
  # === Actuator 端点设置 ===
  endpoints:
    web:
      exposure:
        include: info, health, serviceregistry, features

