server:
  port: 8080

spring:
  application:
    name: micrometer-metrics-prometheus

management:
  endpoints:
    web:
      exposure:
        # 默认情况，Prometheus 监控指标是由 /actuator/prometheus 路径暴露的
        #
        # 需要在 Prometheus 服务器配置文件 prometheus.yml 做如下配置
        # ---------------------------------------------
        # scrape_configs:
        #  - job_name: "micrometer-prometheus"
        #    metrics_path: "/actuator/prometheus"
        #    static_configs:
        #      - targets: ["APP_HOST:8080"]
        # ---------------------------------------------
        include: health,metrics,prometheus

  # 全局指标设置
  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      # 百分位值
      percentiles:
        demo:
          percentiles: [0.25, 0.5, 0.75, 0.90, 0.95]
      # 百分位直方图
      percentiles-histogram:
        demo: true
      # 最小期望值
      minimum-expected-value:
        demo: 90ms
      # 最大期望值
      maximum-expected-value:
        demo: 900ms
      # Service Level Objectives 服务水平目标
      slo:
        demo: 100, 200, 400, 800, 1000

  # === Prometheus 监控指标配置 ===
  prometheus:
    metrics:
      export:
        # 将指标信息推送给 Push Gateway
        #
        # Push Gateway 服务器下载地址：
        #   https://github.com/prometheus/pushgateway
        #
        # 需要在 prometheus.yml 中配置 pushgateway 相关配置
        # ----------------------------------------------
        # scrape_configs:
        #  - job_name: "micrometer-metrics-prometheus"
        #    static_configs:
        #      - targets: ["PUSHGATEWAY_HOST:9091"]
        # -----------------------------------------------
        pushgateway:
          # pushgateway 地址
          base-url: http://localhost:9091
          # 默认 false 关闭推送功能，设置 true 启用
          enabled: false
