server:
  port: 8080

spring:
  application:
    name: micrometer-traces-opentelemetry

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  # 通用指标设置
  metrics:
    tags:
      application: ${spring.application.name}

    # 添加百分位直方图设置
    distribution:
      # 百分位直方图
      percentiles-histogram:
        demo: true
      # 最小期望值 （控制百分位直方图样本起始值）
      minimum-expected-value:
        demo: 90ms
      # 最大期望值（控制百分位直方图样本结束值）
      maximum-expected-value:
        demo: 900ms
      # Service Level Objectives 服务水平目标
      # 在百分位直方图中添加服务水平目标对应的百分位值
      slo:
        demo: 100, 200, 500, 800, 1000, 5000

  # 通用追踪设置
  tracing:
    # 采样率设置
    sampling:
      probability: 1.0

  # === OpenTelemetry Collector 遥测数据收集器配置 ===
  otlp:
    metrics:
      export:
        enabled: true
        step: 5s
        # 默认 OTLP 服务器地址
        url: http://localhost:4318/v1/metrics
    tracing:
      # 默认 OTLP 服务器地址
      endpoint: http://localhost:4318/v1/traces

# 日志控制台输出追踪日志
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
