server:
  port: 8080

spring:
  application:
    name: bus-manager

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  cloud:
    bus:
      # 启用 Spring Cloud Bus，默认 true 启用
      enabled: true
      # 启用总线消息追踪，默认 false 关闭
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        # 暴露总线相关端点 /busrefresh 和 /busenv
        include: busrefresh,busenv