#
# 本配置适用于 Docker Desktop for Mac v.2.1.0.5
#   Engine: v.19.03.5
#   Compose: v.1.24.1
# 更高版本请注意版本配置区别，本版本支持：
#   host.docker.internal
#   参考：https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66
#
version: "3.3"

# 服务列表
services:
  # Loki 服务
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: always
    command: "-config.file=/etc/loki/loki-config.yaml"
    ports:
      - 3100:3100
      - 7946
      - 9095
    volumes:
      - ./docker/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Tempo 服务
  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    restart: always
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - 3200:3200 # tempo
      - 4317 # otlp gRPC
      - 4318 # otlp http
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml

  # OpenTelemetry Collector 服务
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.89.0
    container_name: otel-collector
    restart: always
    ports:
      #- 1888:1888 # pprof extension
      #- 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      #- 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver，SpringBoot 自动装配默认 OTLP via HTTP
      - 55679:55679 # zpages extension
    volumes:
      - ./docker/opentelemetry-collector/otel-collector-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml
    command:
      - "--config=/etc/otelcol-contrib/otel-collector-config.yaml"
    depends_on:
      - tempo
      - loki

  # Prometheus 服务
  prometheus:
    image: bitnami/prometheus:2.48.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - otel-collector

  # Grafana 服务
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    # 指定配置目录
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    # 配置依赖关系
    depends_on:
      - otel-collector
      - prometheus
      - tempo
      - loki
